# ***************** Universidad de los Andes ***********************
# ****** Departamento de Ingeniería de Sistemas y Computación ******
# ********** Arquitectura y diseño de Software - ISIS2503 **********
#
# Infraestructura para laboratorio de Base de datos No SQL
# Elementos a desplegar:
# 1. Firewalls:
#    - nosqld-firewall-django
#    - nosqld-firewall-mongo
# 2. Instancias MVs:
#    - nosqld-django-no-patterns-instance (repositorio clonado y requerimientos instalados)
#    - nosqld-django-patterns-instance (repositorio clonado y requerimientos instalados)
#    - nosqld-mongo-instance (Container Optimized OS sin MongoDB)

resources:
# Firewall rules
- name: nosqld-firewall-django
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges: 
    - 0.0.0.0/0
    targetTags:
    - nosqld-django
    allowed:
    - IPProtocol: TCP
      ports: 
      - 8080
- name: nosqld-firewall-mongo
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
    priority: 1000
    direction: INGRESS
    sourceTags: 
    - nosqld-django
    targetTags:
    - nosqld-mongo
    allowed:
    - IPProtocol: TCP
      ports: 
      - 27017

# Mongo Database instance
- type: compute.v1.instance
  name: nosqld-mongo-instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/cos-cloud/global/images/cos-101-17162-386-64
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
      networkIP: 10.128.0.70
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - nosqld-mongo

# Monitoring app django with no patterns instance
- type: compute.v1.instance
  name: nosqld-django-no-patterns-instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
      networkIP: 10.128.0.71
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - nosqld-django
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt install python3-pip -y
          sudo mkdir /labs
          cd /labs
          sudo git clone https://github.com/ISIS2503/ISIS2503-MonitoringAppNoSQL.git
          cd ISIS2503-MonitoringApp-Auth0
          sudo git checkout nosql-no-patterns
          sudo pip3 install -r requirements.txt

# Monitoring app django with patterns instance
- type: compute.v1.instance
  name: nosqld-django-patterns-instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20240307b
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/<id-proyecto>/global/networks/default
      networkIP: 10.128.0.72
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - nosqld-django
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt install python3-pip -y
          sudo mkdir /labs
          cd /labs
          sudo git clone https://github.com/ISIS2503/ISIS2503-MonitoringAppNoSQL.git
          cd ISIS2503-MonitoringApp-Auth0
          sudo git checkout nosql-patterns
          sudo pip3 install -r requirements.txt